'''Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.'''

a = 1
b = 1
sum = 0

def Fib(max_value, a, b, sum):
    if b % 2 == 0:
        sum+=b
    
    if b > max_value:
        return sum
    
    sum = Fib(max_value, b, b+a, sum)
    return sum


ans = Fib(4e6, a, b, 0)

print(ans)